apiVersion: v1
kind: Service
metadata:
  name: gx-participant-identityhub
  namespace: gx-participant
spec:
  selector:
    app.kubernetes.io/name: gx-participant-identityhub
  ports:
    - name: web
      port: 7080
      targetPort: 7080
    - name: credentials
      port: 7081
      targetPort: 7081
    - name: identity
      port: 7082
      targetPort: 7082
    - name: did
      port: 7083
      targetPort: 7083
    - name: sts
      port: 7086
      targetPort: 7086
