apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gx-participant-postgres
  namespace: gx-participant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
