apiVersion: v1
kind: Secret
metadata:
  name: gx-participant-stack
  namespace: gx-participant
type: Opaque
stringData:
  POSTGRES_USER: participant
  POSTGRES_PASSWORD: participant
  POSTGRES_DB: participant
  VAULT_DEV_ROOT_TOKEN_ID: root
  EDC_VAULT_HASHICORP_TOKEN: root
  EDC_IH_API_SUPERUSER_KEY: c3VwZXItdXNlcg==.c3VwZXItc2VjcmV0LWtleQo=
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: minio123456
