apiVersion: v1
kind: Service
metadata:
  name: gx-participant-vault
  namespace: gx-participant
spec:
  selector:
    app.kubernetes.io/name: gx-participant-vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
